services:
  mysql:
    image: mysql:latest
    container_name: guide-mysql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - "3306:3306"
